"""A small, fixed glossary of terms the chatbot should be able to define
directly -- not everything a user might ask about is a MITRE ATT&CK
technique (covered by _rag_retriever.py's index) or graph data (covered by
_chatbot_queries.py). CVE/CVSS/EPSS/KEV are foundational vulnerability-
management terms outside the MITRE ATT&CK corpus; choke point/blast
radius/attack-path score are this app's own concepts, defined nowhere but
st.caption()/help= text on the dashboard pages. A plain dict with alias
matching is simpler and more reliable than embedding-based retrieval for
this -- the term list is short and fixed, and exact-term questions like
"what is a CVE" don't need semantic search.

Each entry's `scope` matters for how the model should frame it: "general"
terms are standard, industry-wide definitions, independent of this app;
"app_specific" terms are this application's own design choices (most
notably the attack-path scoring formula) and must never be explained as if
they were a generic rule -- every app_specific definition below says "this
app" explicitly so the model has that framing without having to infer it."""

GLOSSARY = {
    "choke_point": {
        "aliases": ["choke point", "choke-point", "chokepoint"],
        "scope": "app_specific",
        "definition": (
            "A choke point is an asset that appears as an interior hop (not the "
            "start or end) on one or more of this app's top-ranked attack paths. "
            "The choke-point count is how many ranked paths pass through it. "
            "Computed by scripts/find_paths.py -- a metric specific to this app, "
            "not a general industry term."
        ),
    },
    "blast_radius": {
        "aliases": ["blast radius", "blast-radius", "blastradius"],
        "scope": "app_specific",
        "definition": (
            "Blast radius is the number of distinct assets reachable (via any "
            "topology relationship, up to 6 hops) from an asset that has at "
            "least one exploitable CVE. Computed live from this app's current "
            "graph -- a metric specific to this app, not a general industry term."
        ),
    },
    "crown_jewel": {
        "aliases": ["crown jewel"],
        "scope": "app_specific",
        "definition": (
            "Crown Jewel is the highest of this app's four asset-criticality "
            "tiers (Crown Jewel, High, Medium, Low). This app ranks attack "
            "paths by how they reach Crown Jewel assets. The tiering is this "
            "app's own asset-classification scheme."
        ),
    },
    "attack_path": {
        "aliases": ["attack path"],
        "scope": "app_specific",
        "definition": (
            "In this app, an attack path is a route from a CVE-exploitable "
            "asset to a Crown Jewel asset through the network topology, "
            "extracted and ranked by scripts/find_paths.py. Only the top 50 "
            "highest-scored paths are kept."
        ),
    },
    "attack_path_score": {
        "aliases": [
            "attack path score", "path score", "pipeline score", "scoring formula",
            "scored", "scoring", "how risky", "why risky",
        ],
        "scope": "app_specific",
        "definition": (
            "This app scores each attack path as: CVSS base score x EPSS score "
            "x target-asset-tier weight x KEV multiplier (2x if the CVE is a "
            "known exploited vulnerability) x exposure multiplier (1.5x if the "
            "source asset is internet-facing) x attack-vector weight, divided "
            "by (hop count + 1). This is a weighting scheme this app's own "
            "pipeline chose to combine severity, exploitation likelihood, and "
            "topology -- it is NOT a generic or industry-standard scoring "
            "formula. CVSS and EPSS themselves are standard scores; combining "
            "them this specific way is this app's design choice."
        ),
    },
    "reasoning_explanation": {
        "aliases": ["reasoning field", "explanation field", "how are explanations generated"],
        "scope": "app_specific",
        "definition": (
            "The Reasoning/explanation text attached to each attack path is "
            "generated by a deterministic template (src/reasoning/explain.py) "
            "that fills in real facts from the path and resolved MITRE ATT&CK "
            "data -- this app's template never states a fact not present in "
            "that data."
        ),
    },
    "cve": {
        "aliases": ["cve", "common vulnerabilities and exposures"],
        "scope": "general",
        "definition": (
            "CVE (Common Vulnerabilities and Exposures) is a publicly "
            "maintained catalog of known software/hardware security "
            "vulnerabilities, each with a unique ID like CVE-2021-26855. This "
            "is a general, industry-standard identifier system, not something "
            "this app invented."
        ),
    },
    "cvss": {
        "aliases": ["cvss", "common vulnerability scoring system"],
        "scope": "general",
        "definition": (
            "CVSS (Common Vulnerability Scoring System) is a general, "
            "industry-standard 0-10 severity score for a vulnerability, "
            "published alongside its CVE entry. This app uses it as one input "
            "into its own attack-path scoring formula."
        ),
    },
    "epss": {
        "aliases": ["epss", "exploit prediction scoring system"],
        "scope": "general",
        "definition": (
            "EPSS (Exploit Prediction Scoring System) is a general, "
            "industry-standard score (0-1) estimating the probability a "
            "vulnerability will be exploited in the wild in the next 30 days, "
            "maintained by FIRST.org. This app uses it as one input into its "
            "own attack-path scoring formula."
        ),
    },
    "kev": {
        "aliases": ["kev", "known exploited vulnerabilities"],
        "scope": "general",
        "definition": (
            "KEV (Known Exploited Vulnerabilities) is a catalog maintained by "
            "CISA (a US government agency) listing CVEs with confirmed "
            "real-world exploitation. It's a general, publicly maintained "
            "list, not specific to this app; this app uses KEV membership as "
            "a multiplier in its own attack-path scoring formula."
        ),
    },
}


def relevant_glossary_entries(question: str) -> list[dict]:
    lowered = question.lower()
    return [
        {"term": key, **entry}
        for key, entry in GLOSSARY.items()
        if any(alias in lowered for alias in entry["aliases"])
    ]
